"" General
set number          " Show line numbers
set showbreak=+++   " Wrap-broken line prefix
set showmatch       " Highlight matching brace
set visualbell      " Use visual bell (no beeping) 
set hlsearch        " Highlight all search results
set smartcase       " Enable smart-case search
set incsearch       " Searches for strings incrementally
set autoindent      " Auto-indent new lines
set expandtab       " Use spaces instead of tabs
set shiftwidth=4    " Number of auto-indent spaces
set smartindent     " Enable smart-indent
set smarttab        " Enable smart-tabs
set softtabstop=4   " Number of spaces per Tab
syntax on           " Enable syntax highlighting

"" Advanced

set ruler                       " Show row and column ruler information
set autochdir                   " Change working directory to open buffer
set undolevels=1000             " Number of undo levels
set backspace=indent,eol,start  " Backspace behaviour


"" Generated by VimConfig.com

" Gherkin syntax highlight
au Bufread,BufNewFile *.feature set filetype=gherkin
au! Syntax gherkin source ~/.vim/syntax/cucumber.vim
